version: '3.8'

services:
  postgres:
    image: docker.io/postgres:14
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: passw0rd
    volumes:
      - kc-data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    command: start-dev -Djgroups.dns.query=keycloak
    environment:
      KC_CACHE: ispn
      KC_CACHE_STACK: kubernetes
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: '5432'
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: passw0rd
      KC_PROXY: edge
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: '8000'
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    deploy:
      replicas: 2
      endpoint_mode: dnsrr

  lb:
    image: docker.io/nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:8000"

volumes:
  kc-data:
    name: keycloak-workshop-pg-data
