volumes:
  kc-data:
    name: keycloak-workshop-pg-data
  jaeger-tmp:
    name: keycloak-workshop-jaeger-tmp

networks:
  kc:
    name: keycloak-workshop

services:
  postgres:
    image: docker.io/postgres:18-alpine
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: passw0rd
    ports:
      - "5432:5432"
    volumes:
      - kc-data:/var/lib/postgresql
    networks:
      - kc

  lb:
    image: docker.io/traefik:v3
    command:
      - "--log.level=INFO"
      - "--providers.docker=true"
      - "--providers.docker.network=keycloak-workshop"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.filename=/etc/traefik/dynamic.yml"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:8443"
      - "--entrypoints.kc1mgmt.address=:9001"
      - "--entrypoints.kc2mgmt.address=:9002"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/tls:ro
      - ./traefik-dynamic.yml:/etc/traefik/dynamic.yml:ro
    ports:
      - "8443:8443"
      - "9001:9001"
      - "9002:9002"
    networks:
      - kc
    depends_on:
      - keycloak

  mail:
    image: docker.io/axllent/mailpit:latest
    ports:
      - "8025:8025"
    networks:
      - kc
