volumes:
  kc-data:
    name: keycloak-workshop-pg-data
  jaeger-tmp:
    name: keycloak-workshop-jaeger-tmp

networks:
  kc:
    name: keycloak-workshop

services:
  postgres:
    image: docker.io/postgres:18-alpine
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: passw0rd
    ports:
      - "5432:5432"
    volumes:
      - kc-data:/var/lib/postgresql/data
    networks:
      - kc
  
  lb:
    image: docker.io/nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/tls
    ports:
      - "8443:8443"
      - "9001:9001"
      - "9002:9002"
    networks:
      - kc
    depends_on:
      - keycloak
  
  mail:
    image: docker.io/axllent/mailpit:latest
    ports:
      - "8025:8025"
    networks:
      - kc
