volumes:
  kc-data:
    name: keycloak-workshop-pg-data

networks:
  kc:
    name: keycloak-workshop

services:
  postgres:
    image: docker.io/postgres:18-alpine
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: passw0rd
    ports:
      - "5432:5432"
    volumes:
      - kc-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 1s
      timeout: 1s
      retries: 30
      start_period: 2s
    networks:
      - kc

  ldap:
    image: ghcr.io/dasniko/flintstones-ldap:latest
    networks:
      - kc

  mail:
    image: docker.io/axllent/mailpit:latest
    ports:
      - "8025:8025"
    networks:
      - kc
