volumes:
  kc-data:
    name: keycloak-workshop-pg-data
  jaeger-tmp:
    name: keycloak-workshop-jaeger-tmp

networks:
  kc:
    name: keycloak-workshop

services:
  postgres:
    image: docker.io/postgres:18-alpine
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: passw0rd
    ports:
      - "5432:5432"
    volumes:
      - kc-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    networks:
      - kc

  lb:
    image: docker.io/nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
      - ./certs:/etc/certs:ro
    ports:
      - "8443:8443"
      - "9000:9000"
    networks:
      - kc
    depends_on:
      - keycloak

  mail:
    image: docker.io/axllent/mailpit:latest
    ports:
      - "8025:8025"
    networks:
      - kc
