include:
  - commons.yml

services:
  keycloak:
    image: keycloak-workshop
    build: .
    command: start --optimized
    environment:
      # tbc...
    deploy:
      replicas: 2
    networks:
      - kc
    depends_on:
      - postgres

  jaeger:
    image: docker.io/jaegertracing/all-in-one:latest
    command: --log-level=error
    ports:
      - "16686:16686"
    volumes:
      - jaeger-tmp:/tmp
    networks:
      - kc
