include:
  - commons.yml

services:
  keycloak:
    image: keycloak-workshop
    build: .
    command: start --optimized --import-realm
    environment:
      # HTTP_PROXY: http://proxy:3128
      # HTTPS_PROXY: http://proxy:3128
      # NO_PROXY: 'localhost,bookshop,ldap,127.0.0.0/8'
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: '5432'
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: passw0rd
      KC_PROXY_HEADERS: xforwarded
      KC_HOSTNAME: 'https://localhost:8443'
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: 'true'
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/certs/localhost.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/certs/localhost.key
      KC_TRUSTSTORE_PATHS: /opt/keycloak/certs/rootCA.crt
      KC_TLS_HOSTNAME_VERIFIER: ANY
      KC_LOG_CONSOLE_INCLUDE_TRACE: 'false'
      KC_TRACING_SAMPLER_RATIO: "0.0"
      KC_SPI_EVENTS_LISTENER__EMAIL__INCLUDE_EVENTS: login_error,update_credential,remove_credential,user_disabled_by_temporary_lockout
      KC_SPI_EVENTS_LISTENER__JBOSS_LOGGING__SUCCESS_LEVEL: info
    volumes:
      - ./bookshop-realm.json:/opt/keycloak/data/import/bookshop-realm.json
    deploy:
      replicas: 2
    networks:
      - kc
    depends_on:
      - postgres

  ldap:
    image: ghcr.io/dasniko/flintstones-ldap:latest
    networks:
      - kc

  bookshop:
    image: ghcr.io/dasniko/keycloak-bookshop-demo:0.0.11
    command: [ "wait-for-it.sh", "keycloak-workshop-keycloak-1:8443", "--", "/deployments/entrypoint.sh" ]
    environment:
      WAITFORIT_TIMEOUT: '120'
      AUTH_SERVER_URL: http://lb:80/realms/bookshop
      AUTH_SERVER_PUBLIC_URL: https://localhost:8443/realms/bookshop
      SHOP_CLIENT_ID: shop
      SHOP_CLIENT_SECRET: n/a
    ports:
      - "3000:3000"
      - "8081:8081"
      - "8083:8083"
    volumes:
      - ./bookshop-keycloak.json:/usr/share/nginx/html/keycloak.json
    networks:
      - kc
