volumes:
  kc-data:
    name: keycloak-workshop-pg-data

services:
  postgres:
    image: docker.io/postgres:17
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: passw0rd
    ports:
      - "5432:5432"
    volumes:
      - kc-data:/var/lib/postgresql/data

  mail:
    image: docker.io/axllent/mailpit:latest
    ports:
      - "8025:8025"
  
  keycloak:
    image: quay.io/keycloak/keycloak:26.1
    command: start --import-realm
    environment:
      # HTTP_PROXY: http://proxy:3128
      # HTTPS_PROXY: http://proxy:3128
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: '5432'
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: passw0rd
      KC_PROXY_HEADERS: xforwarded
      KC_HOSTNAME: 'https://localhost'
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: 'true'
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/certs/localhost.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/certs/localhost.key
      KC_TRUSTSTORE_PATHS: /opt/keycloak/certs/rootCA.crt
      KC_FEATURES: passkeys,recovery-codes,update-email,quick-theme
    deploy:
      replicas: 2
      endpoint_mode: dnsrr
    volumes:
      - ./bookshop-realm.json:/opt/keycloak/data/import/bookshop-realm.json
      - ./providers:/opt/keycloak/providers
      - ./themes:/opt/keycloak/themes
      - ./certs:/opt/keycloak/certs
    depends_on:
      - postgres

  lb:
    image: docker.io/nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/tls
    ports:
      - "443:443"
    depends_on:
      - keycloak

  ldap:
    image: docker.io/dasniko/openldap_flintstones:latest
    # bind user: cn=keycloak,dc=stoneage,dc=local

  bookshop:
    profiles:
      - books
    image: docker.io/dasniko/bookshop:0.0.8
    command: [ "wait-for-it.sh", "keycloak-workshop-keycloak-1:8443", "--", "/deployments/entrypoint.sh" ]
    environment:
      WAITFORIT_TIMEOUT: '120'
      AUTH_SERVER_URL: http://lb:80/realms/bookshop
      SHOP_CLIENT_ID: shop
      SHOP_CLIENT_SECRET: LuWb24brRRlkgt2ltd79BJEw6xV6FPpV
    ports:
      - "3000:3000"
      - "8081:8081"
      - "8083:8083"
    volumes:
      - ./bookshop-keycloak.json:/usr/share/nginx/html/keycloak.json
