services:
  postgres:
    image: docker.io/postgres:16
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: passw0rd
    ports:
      - "5432:5432"
    volumes:
      - kc-data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    command: start-dev --import-realm
    environment:
      # HTTP_PROXY: http://proxy:3128
      # HTTPS_PROXY: http://proxy:3128
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: '5432'
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: passw0rd
      KC_HOSTNAME: 'http://localhost:8080'
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: 'true'
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/certs/localhost.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/certs/localhost.key
      KC_TRUSTSTORE_PATHS: /opt/keycloak/certs/rootCA.crt
      KC_TLS_HOSTNAME_VERIFIER: ANY
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./providers:/opt/keycloak/providers
      - ./themes:/opt/keycloak/themes
      - ./bookshop-realm.json:/opt/keycloak/data/import/bookshop-realm.json
      - ./certs:/opt/keycloak/certs

  mail:
    image: docker.io/axllent/mailpit:latest
    ports:
      - "8025:8025"

  ldap:
    image: docker.io/osixia/openldap:latest
    environment:
      # bind user: cn=keycloak,dc=corp,dc=acme,dc=local
      # bind password: keycloak
      LDAP_LOG_LEVEL: '0'
      LDAP_ORGANISATION: Acme Inc.
      LDAP_DOMAIN: corp.acme.local
      # admin User: cn=admin,dc=corp,dc=acme,dc=local
      LDAP_ADMIN_PASSWORD: admin
      LDAP_REMOVE_CONFIG_AFTER_SETUP: 'false'
      LDAP_SEED_INTERNAL_LDIF_PATH: /acme/openldap/ldif/acme.ldif
      LDAP_TLS: "true"
      LDAP_TLS_CRT_FILENAME: "ldap.crt"
      LDAP_TLS_KEY_FILENAME: "ldap.key"
      LDAP_TLS_CA_CRT_FILENAME: "rootCA.crt"
      LDAP_TLS_VERIFY_CLIENT: never
    volumes:
      - ./acme.ldif:/acme/openldap/ldif/acme.ldif
      - ./certs:/container/service/slapd/assets/certs

  ldap_admin:
    image: docker.io/osixia/phpldapadmin:latest
    command: --loglevel warning
    ports:
      - "8090:80"
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap
      PHPLDAPADMIN_HTTPS: 'false'
    depends_on:
      - ldap

  bookshop:
    image: docker.io/dasniko/bookshop:0.0.8
    command: [ "wait-for-it.sh", "keycloak:8080", "--", "/deployments/entrypoint.sh" ]
    environment:
      WAITFORIT_TIMEOUT: '120'
      AUTH_SERVER_URL: http://keycloak:8080/realms/bookshop
      SHOP_CLIENT_ID: shop
      SHOP_CLIENT_SECRET: 08d171bf-ba03-44db-8279-f678d68021d7
    ports:
      - "3000:3000"
      - "8081:8081"
      - "8083:8083"
    volumes:
      - ./bookshop-keycloak.json:/usr/share/nginx/html/keycloak.json

volumes:
  kc-data:
    name: keycloak-workshop-pg-data
