volumes:
  kc-data:
    name: keycloak-workshop-pg-data

services:
  postgres:
    image: docker.io/postgres:17
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: passw0rd
    ports:
      - "5432:5432"
    volumes:
      - kc-data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.1
    command: start --import-realm
    environment:
      # HTTP_PROXY: http://proxy:3128
      # HTTPS_PROXY: http://proxy:3128
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_BOOTSTRAP_ADMIN_CLIENT_ID: admin-client
      KC_BOOTSTRAP_ADMIN_CLIENT_SECRET: S3cr3t!
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: '5432'
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: passw0rd
      KC_PROXY_HEADERS: xforwarded
      KC_HOSTNAME: 'https://localhost'
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: 'true'
      #KC_HOSTNAME_STRICT: 'false'
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/certs/localhost.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/certs/localhost.key
      KC_TRUSTSTORE_PATHS: /opt/keycloak/certs/rootCA.crt
      #KC_TLS_HOSTNAME_VERIFIER: ANY
      KC_FEATURES: passkeys,recovery-codes,update-email,user-event-metrics,quick-theme,transient-users
      KC_HEALTH_ENABLED: 'true'
      KC_METRICS_ENABLED: 'true'
      KC_EVENT_METRICS_USER_ENABLED: 'true'
      KC_EVENT_METRICS_USER_EVENTS: login,logout,refresh_token,register,update_credential
      KC_EVENT_METRICS_USER_TAGS: realm,idp,clientId
      KC_TRACING_ENABLED: 'true'
      KC_TRACING_ENDPOINT: 'http://jaeger:4317'
      KC_LOG_CONSOLE_INCLUDE_TRACE: 'false'
    deploy:
      replicas: 2
      endpoint_mode: dnsrr
    volumes:
      - ./bookshop-realm.json:/opt/keycloak/data/import/bookshop-realm.json
      - ./providers:/opt/keycloak/providers
      - ./themes:/opt/keycloak/themes
      - ./certs:/opt/keycloak/certs
      - ./keycloak-benchmark:/opt/keycloak/benchmark
    depends_on:
      - postgres

  lb:
    image: docker.io/nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/tls
    ports:
      - "80:80"
      - "443:443"
      - "9000:9000"
    depends_on:
      - keycloak

  mail:
    image: docker.io/axllent/mailpit:latest
    ports:
      - "8025:8025"

  ldap:
    image: docker.io/osixia/openldap:latest
    environment:
      # bind user: cn=keycloak,dc=corp,dc=acme,dc=local
      # bind password: keycloak
      LDAP_LOG_LEVEL: '0'
      LDAP_ORGANISATION: Acme Inc.
      LDAP_DOMAIN: corp.acme.local
      # admin User: cn=admin,dc=corp,dc=acme,dc=local
      LDAP_ADMIN_PASSWORD: admin
      LDAP_REMOVE_CONFIG_AFTER_SETUP: 'false'
      LDAP_SEED_INTERNAL_LDIF_PATH: /acme/openldap/ldif/acme.ldif
      LDAP_TLS: "true"
      LDAP_TLS_CRT_FILENAME: "ldap.crt"
      LDAP_TLS_KEY_FILENAME: "ldap.key"
      LDAP_TLS_CA_CRT_FILENAME: "rootCA.crt"
      LDAP_TLS_VERIFY_CLIENT: never
    volumes:
      - ./acme.ldif:/acme/openldap/ldif/acme.ldif
      - ./certs:/container/service/slapd/assets/certs

  bookshop:
    image: docker.io/dasniko/bookshop:0.0.8
    command: [ "wait-for-it.sh", "keycloak-workshop-keycloak-1:8443", "--", "/deployments/entrypoint.sh" ]
    environment:
      WAITFORIT_TIMEOUT: '120'
      AUTH_SERVER_URL: http://lb:80/realms/bookshop
      SHOP_CLIENT_ID: shop
      SHOP_CLIENT_SECRET: LuWb24brRRlkgt2ltd79BJEw6xV6FPpV
    ports:
      - "3000:3000"
      - "8081:8081"
      - "8083:8083"
    volumes:
      - ./bookshop-keycloak.json:/usr/share/nginx/html/keycloak.json

  jaeger:
    image: docker.io/jaegertracing/all-in-one:latest
    command: --log-level=error
    ports:
      - "16686:16686"
