volumes:
  kc-data:
    name: keycloak-workshop-pg-data

services:
  postgres:
    image: docker.io/postgres:17
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: passw0rd
    ports:
      - "5432:5432"
    volumes:
      - kc-data:/var/lib/postgresql/data

  mail:
    image: docker.io/axllent/mailpit:latest
    ports:
      - "8025:8025"
