include:
  - commons.yml

services:
  keycloak:
    image: keycloak-workshop
    build: .
    pull_policy: build
    command: start --optimized
    environment:
      # tbc...
    volumes:
      - ./certs:/opt/keycloak/certs:ro
    init: true
    stop_grace_period: 2s
    deploy:
      replicas: 2
    networks:
      - kc
    depends_on:
      postgres:
        condition: service_healthy

  lb:
    image: docker.io/nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
      - ./certs:/etc/certs:ro
    ports:
      - "8443:8443"
      - "9001:9001"
      - "9002:9002"
    networks:
      - kc
    depends_on:
      - keycloak

  jaeger:
    image: docker.io/jaegertracing/all-in-one:latest
    command: --log-level=error
    ports:
      - "16686:16686"
    volumes:
      - jaeger-tmp:/tmp
    networks:
      - kc

volumes:
  jaeger-tmp:
    name: keycloak-workshop-jaeger-tmp
