// HTTP Collection for REST Client for Visual Studio Code
// https://marketplace.visualstudio.com/items?itemName=humao.rest-client

###

# @name Healthcheck
GET https://localhost:9000/health

###

# @name Metrics
GET https://localhost:9000/metrics

###

# @name UserToken
POST https://localhost/realms/bookshop/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

username=john.doe
&password=test
&grant_type=password
&client_id=admin-cli
&scope=openid

###

# @name ClientToken
POST https://localhost/realms/bookshop/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=shop
&client_secret=LuWb24brRRlkgt2ltd79BJEw6xV6FPpV
&grant_type=client_credentials

###

# @name UserInfo
POST https://localhost/realms/bookshop/protocol/openid-connect/userinfo
Content-Type: application/x-www-form-urlencoded

access_token={{UserToken.response.body.$.access_token}}
