FROM osixia/openldap:latest
LABEL maintainer="Niko Köbler <info@n-k.de>"

ADD bootstrap /container/service/slapd/assets/config/bootstrap
ADD certs /container/service/slapd/assets/certs
ADD environment /container/environment/01-custom
