name: Cleanup inactive users
on: user-authenticated
concurrency:
  restart-in-progress: "true"
if: has-identity-provider-link(oidc)
steps:
  - uses: notify-user
    after: 30s
    with:
      message: You will be disabled and removed shortly if you do not authenticate!
  - uses: disable-user
    after: 30s
  - uses: delete-user
    after: 1m
